stages:
  - docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: 1
  GIT_DEPTH: "0"

services:
  - docker:20.10.16-dind

docker:
  stage: docker
  image: docker:20.10.16
  before_script:
    - apk add --no-cache bash curl wget docker-compose
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d
  only:
    - traore-cheikh-isiburger
